// <auto-generated />
using ApiWallet.Data;

namespace ApiWallet.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190604001142_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiWallet.Models.Fundo", b =>
                {
                    b.Property<int>("FundoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FundoId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name");

                    b.Property<decimal>("Qty")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnName("Qty")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal>("Value")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnName("Value")
                        .HasColumnType("Decimal(10,2)");

                    b.HasKey("FundoId");

                    b.ToTable("Fundos");
                });
#pragma warning restore 612, 618
        }
    }
}
